#include<iostream>
#include<dir.h>
#include<windows.h>
#include<sstream>
#include<conio.h>
#include<process.h>
#include<stdio.h>
#include<fstream>
using namespace std;
#include "makefil_11.h"
#include "mkdir_11.h"
#include "remove_11.h"
#include "dir_11.h"
#include "describe_11.h"
#include "upp_4.h"
 

string task_3;
string cd_33="cd",mkfile_33="mkfile",mkdir_33="mkdir",rm_33="rm",dir_33="dir",des_33="des";
ostringstream buf;

 	void postmain_3(string &command_6,string &command_7,string &m,string &n,string &o,string &p,string &task_3){
 		
 	cout<<endl;cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
		 	
	ostringstream buf;
	buf<<".\\Outputs"<<"\\"<<command_6<<"\\"<<command_7<<"\\";
	CreateDirectory(buf.str().c_str(),NULL);
    if(task_3==mkfile_33){
	makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
	if(task_3==mkfile_33){
			makefil_11(command_6,command_7,m);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		if(task_3==mkdir_33){
			mkdir_11(command_6,command_7,p);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		   if(task_3==des_33){
			describe_11(command_6,command_7,n);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==rm_33){
			destroy_11(command_6,command_7,o);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==dir_33){
			direct_11(command_6,command_7);
			cout<<"/"<<command_6<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
			}else if(task_3==mkdir_33){
				mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
				if(task_3==mkfile_33){
	        makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
	       	if(task_3==mkfile_33){
			makefil_11(command_6,command_7,m);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==mkdir_33){
			mkdir_11(command_6,command_7,p);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		   if(task_3==des_33){
			describe_11(command_6,command_7,n);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==rm_33){
			destroy_11(command_6,command_7,o);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==dir_33){
			direct_11(command_6,command_7);
			cout<<"/"<<command_6<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}}}
			else if(task_3==des_33){
			describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){
	        makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
	       	if(task_3==mkfile_33){
			makefil_11(command_6,command_7,m);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==mkdir_33){
			mkdir_11(command_6,command_7,p);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		     if(task_3==des_33){
			describe_11(command_6,command_7,n);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==rm_33){
			destroy_11(command_6,command_7,o);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==dir_33){
			direct_11(command_6,command_7);
			cout<<"/"<<command_6<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}}}
			else if(task_3==rm_33){
			destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){
			makefil_11(command_6,command_7,m);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==mkdir_33){
			mkdir_11(command_6,command_7,p);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		    if(task_3==des_33){
			describe_11(command_6,command_7,n);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==rm_33){
			destroy_11(command_6,command_7,o);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==dir_33){
			direct_11(command_6,command_7);
			cout<<"/"<<command_6<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}}
			else if(task_3==dir_33){
			direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;		
			if(task_3==mkfile_33){
			makefil_11(command_6,command_7,m);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==mkdir_33){
			mkdir_11(command_6,command_7,p);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
		    if(task_3==des_33){
			describe_11(command_6,command_7,n);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==rm_33){
			destroy_11(command_6,command_7,o);
			cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}
	       	if(task_3==dir_33){
			direct_11(command_6,command_7);
			cout<<"/"<<command_6<<">";cin>>task_3;cout<<endl;
			if(task_3==mkfile_33){makefil_11(command_6,command_7,m);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==mkdir_33){mkdir_11(command_6,command_7,p);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==des_33){describe_11(command_6,command_7,n);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==rm_33){destroy_11(command_6,command_7,o);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}
	       	if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;
			if(task_3==dir_33){direct_11(command_6,command_7);cout<<"/"<<command_6<<"/"<<command_7<<">";cin>>task_3;cout<<endl;}}}}}		

